version: '3'
services:
  db:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: prestashop
      MYSQL_DATABASE: prestashop
      MYSQL_USER: prestashop
      MYSQL_PASSWORD: prestashop

  web:
    image: prestashop/prestashop
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db
    environment:
      DB_SERVER: db
      DB_NAME: prestashop
      DB_USER: prestashop
      DB_PASSWD: prestashop
#      PS_INSTALL_AUTO: 1
#      PS_ERASE_DB: 1
      PS_FOLDER_INSTALL: install-dev
      PS_FOLDER_ADMIN: admin-dev